### PR TITLE
JS implementation

### PR DESCRIPTION
**Pull request by Keytus**

### CODE REVIEW

**Comment by nastik1811** [comment]
Why does your PR include all the code from the previous one?

**Comment by Keytus** [comment]
Cause i forget pull main branch after merge on Github, so when i create Lab4 branch it was empty. Pls, check src folder with js.

**Comment by nastik1811** [comment]
you can merge `main` to `Lab4`
it's hard to review

**Comment by Keytus** [comment]
Merged.Please, check.

**Review by nastik1811 — APPROVED** [review]

**Pull request merged**
